# Generated by Django 3.1.5 on 2021-01-20 15:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pco_license_image', models.ImageField(upload_to=core.models.PathRename('8e764dc5506547c0a669117be330df49', 'pco_image'))),
                ('driver_license_image', models.ImageField(upload_to=core.models.PathRename('8e764dc5506547c0a669117be330df49', 'driver_image'))),
            ],
        ),
    ]
