# Generated by Django 3.1.5 on 2021-01-20 15:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='driver_license_image',
            field=models.ImageField(upload_to=core.models.PathRename('b6fadd24491247d1b11f625c1d36f1e7', 'driver_image')),
        ),
        migrations.AlterField(
            model_name='license',
            name='pco_license_image',
            field=models.ImageField(upload_to=core.models.PathRename('b6fadd24491247d1b11f625c1d36f1e7', 'pco_image')),
        ),
    ]
