# Generated by Django 3.1.5 on 2021-01-25 13:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210120_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=30)),
                ('driver_original_image', models.CharField(max_length=50000)),
                ('driver_face', models.CharField(max_length=50000)),
                ('Fullname', models.CharField(max_length=255)),
                ('DOB', models.CharField(max_length=15)),
                ('POB', models.CharField(max_length=255)),
                ('Issued_Date', models.CharField(max_length=15)),
                ('Renew_Due_Date', models.CharField(max_length=15)),
                ('Issuing_authority', models.CharField(max_length=50)),
                ('License_Number', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=255)),
                ('Entitlement_categories', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PCOLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=30)),
                ('pco_original_image', models.CharField(max_length=50000)),
                ('pco_face', models.CharField(max_length=50000)),
                ('Fullname', models.CharField(max_length=255)),
                ('License_Number', models.CharField(max_length=25)),
                ('Expiry_date', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='license',
            name='driver_license_image',
            field=models.ImageField(upload_to=core.models.PathRename('images', 'driver_image')),
        ),
        migrations.AlterField(
            model_name='license',
            name='pco_license_image',
            field=models.ImageField(upload_to=core.models.PathRename('images', 'pco_image')),
        ),
    ]
